import { WagmiProviderContext } from "@/components/providers/wagmi-provider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { TRPCReactProvider } from "@/trpc/react";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TRPCReactProvider>
          <WagmiProviderContext>
            <AuthProvider>
              <Navbar />
              <main>
                {children}
              </main>
            </AuthProvider>
          </WagmiProviderContext>
        </TRPCReactProvider>
      </body>
    </html>
  );
}